# Generated by Django 5.1.3 on 2025-01-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
